// Country helpers: name + domain suffixes for all 193 UN member states

export const countries = {
  af: { name: 'Afghanistan', suffixes: ['.af'] },
  al: { name: 'Albania', suffixes: ['.al'] },
  dz: { name: 'Algeria', suffixes: ['.dz'] },
  ad: { name: 'Andorra', suffixes: ['.ad'] },
  ao: { name: 'Angola', suffixes: ['.ao'] },
  ag: { name: 'Antigua and Barbuda', suffixes: ['.ag'] },
  ar: { name: 'Argentina', suffixes: ['.ar', '.com.ar'] },
  am: { name: 'Armenia', suffixes: ['.am'] },
  au: { name: 'Australia', suffixes: ['.au', '.com.au'] },
  at: { name: 'Austria', suffixes: ['.at'] },
  az: { name: 'Azerbaijan', suffixes: ['.az'] },
  bs: { name: 'Bahamas', suffixes: ['.bs'] },
  bh: { name: 'Bahrain', suffixes: ['.bh'] },
  bd: { name: 'Bangladesh', suffixes: ['.bd', '.com.bd'] },
  bb: { name: 'Barbados', suffixes: ['.bb'] },
  by: { name: 'Belarus', suffixes: ['.by'] },
  be: { name: 'Belgium', suffixes: ['.be'] },
  bz: { name: 'Belize', suffixes: ['.bz'] },
  bj: { name: 'Benin', suffixes: ['.bj'] },
  bt: { name: 'Bhutan', suffixes: ['.bt'] },
  bo: { name: 'Bolivia', suffixes: ['.bo', '.com.bo'] },
  ba: { name: 'Bosnia and Herzegovina', suffixes: ['.ba'] },
  bw: { name: 'Botswana', suffixes: ['.bw'] },
  br: { name: 'Brazil', suffixes: ['.br', '.com.br'] },
  bn: { name: 'Brunei', suffixes: ['.bn'] },
  bg: { name: 'Bulgaria', suffixes: ['.bg'] },
  bf: { name: 'Burkina Faso', suffixes: ['.bf'] },
  bi: { name: 'Burundi', suffixes: ['.bi'] },
  cv: { name: 'Cabo Verde', suffixes: ['.cv'] },
  kh: { name: 'Cambodia', suffixes: ['.kh'] },
  cm: { name: 'Cameroon', suffixes: ['.cm'] },
  ca: { name: 'Canada', suffixes: ['.ca'] },
  cf: { name: 'Central African Republic', suffixes: ['.cf'] },
  td: { name: 'Chad', suffixes: ['.td'] },
  cl: { name: 'Chile', suffixes: ['.cl'] },
  cn: { name: 'China', suffixes: ['.cn', '.com.cn'] },
  co: { name: 'Colombia', suffixes: ['.co', '.com.co'] },
  km: { name: 'Comoros', suffixes: ['.km'] },
  cg: { name: 'Congo', suffixes: ['.cg'] },
  cd: { name: 'DR Congo', suffixes: ['.cd'] },
  cr: { name: 'Costa Rica', suffixes: ['.cr'] },
  ci: { name: 'Côte d\'Ivoire', suffixes: ['.ci'] },
  hr: { name: 'Croatia', suffixes: ['.hr'] },
  cu: { name: 'Cuba', suffixes: ['.cu'] },
  cy: { name: 'Cyprus', suffixes: ['.cy'] },
  cz: { name: 'Czechia', suffixes: ['.cz'] },
  dk: { name: 'Denmark', suffixes: ['.dk'] },
  dj: { name: 'Djibouti', suffixes: ['.dj'] },
  dm: { name: 'Dominica', suffixes: ['.dm'] },
  do: { name: 'Dominican Republic', suffixes: ['.do', '.com.do'] },
  ec: { name: 'Ecuador', suffixes: ['.ec', '.com.ec'] },
  eg: { name: 'Egypt', suffixes: ['.eg', '.com.eg'] },
  sv: { name: 'El Salvador', suffixes: ['.sv'] },
  gq: { name: 'Equatorial Guinea', suffixes: ['.gq'] },
  er: { name: 'Eritrea', suffixes: ['.er'] },
  ee: { name: 'Estonia', suffixes: ['.ee'] },
  sz: { name: 'Eswatini', suffixes: ['.sz'] },
  et: { name: 'Ethiopia', suffixes: ['.et'] },
  fj: { name: 'Fiji', suffixes: ['.fj'] },
  fi: { name: 'Finland', suffixes: ['.fi'] },
  fr: { name: 'France', suffixes: ['.fr'] },
  ga: { name: 'Gabon', suffixes: ['.ga'] },
  gm: { name: 'Gambia', suffixes: ['.gm'] },
  ge: { name: 'Georgia', suffixes: ['.ge'] },
  de: { name: 'Germany', suffixes: ['.de'] },
  gh: { name: 'Ghana', suffixes: ['.gh', '.com.gh'] },
  gr: { name: 'Greece', suffixes: ['.gr'] },
  gd: { name: 'Grenada', suffixes: ['.gd'] },
  gt: { name: 'Guatemala', suffixes: ['.gt', '.com.gt'] },
  gn: { name: 'Guinea', suffixes: ['.gn'] },
  gw: { name: 'Guinea-Bissau', suffixes: ['.gw'] },
  gy: { name: 'Guyana', suffixes: ['.gy'] },
  ht: { name: 'Haiti', suffixes: ['.ht'] },
  hn: { name: 'Honduras', suffixes: ['.hn'] },
  hu: { name: 'Hungary', suffixes: ['.hu'] },
  is: { name: 'Iceland', suffixes: ['.is'] },
  in: { name: 'India', suffixes: ['.in', '.co.in'] },
  id: { name: 'Indonesia', suffixes: ['.id', '.co.id'] },
  ir: { name: 'Iran', suffixes: ['.ir'] },
  iq: { name: 'Iraq', suffixes: ['.iq'] },
  ie: { name: 'Ireland', suffixes: ['.ie'] },
  il: { name: 'Israel', suffixes: ['.il', '.co.il'] },
  it: { name: 'Italy', suffixes: ['.it'] },
  jm: { name: 'Jamaica', suffixes: ['.jm'] },
  jp: { name: 'Japan', suffixes: ['.jp', '.co.jp'] },
  jo: { name: 'Jordan', suffixes: ['.jo'] },
  kz: { name: 'Kazakhstan', suffixes: ['.kz'] },
  ke: { name: 'Kenya', suffixes: ['.ke', '.co.ke'] },
  ki: { name: 'Kiribati', suffixes: ['.ki'] },
  kp: { name: 'North Korea', suffixes: ['.kp'] },
  kr: { name: 'South Korea', suffixes: ['.kr', '.co.kr'] },
  kw: { name: 'Kuwait', suffixes: ['.kw'] },
  kg: { name: 'Kyrgyzstan', suffixes: ['.kg'] },
  la: { name: 'Laos', suffixes: ['.la'] },
  lv: { name: 'Latvia', suffixes: ['.lv'] },
  lb: { name: 'Lebanon', suffixes: ['.lb'] },
  ls: { name: 'Lesotho', suffixes: ['.ls'] },
  lr: { name: 'Liberia', suffixes: ['.lr'] },
  ly: { name: 'Libya', suffixes: ['.ly'] },
  li: { name: 'Liechtenstein', suffixes: ['.li'] },
  lt: { name: 'Lithuania', suffixes: ['.lt'] },
  lu: { name: 'Luxembourg', suffixes: ['.lu'] },
  mg: { name: 'Madagascar', suffixes: ['.mg'] },
  mw: { name: 'Malawi', suffixes: ['.mw'] },
  my: { name: 'Malaysia', suffixes: ['.my', '.com.my'] },
  mv: { name: 'Maldives', suffixes: ['.mv'] },
  ml: { name: 'Mali', suffixes: ['.ml'] },
  mt: { name: 'Malta', suffixes: ['.mt'] },
  mh: { name: 'Marshall Islands', suffixes: ['.mh'] },
  mr: { name: 'Mauritania', suffixes: ['.mr'] },
  mu: { name: 'Mauritius', suffixes: ['.mu'] },
  mx: { name: 'Mexico', suffixes: ['.mx', '.com.mx'] },
  fm: { name: 'Micronesia', suffixes: ['.fm'] },
  md: { name: 'Moldova', suffixes: ['.md'] },
  mc: { name: 'Monaco', suffixes: ['.mc'] },
  mn: { name: 'Mongolia', suffixes: ['.mn'] },
  me: { name: 'Montenegro', suffixes: ['.me'] },
  ma: { name: 'Morocco', suffixes: ['.ma'] },
  mz: { name: 'Mozambique', suffixes: ['.mz'] },
  mm: { name: 'Myanmar', suffixes: ['.mm'] },
  na: { name: 'Namibia', suffixes: ['.na'] },
  nr: { name: 'Nauru', suffixes: ['.nr'] },
  np: { name: 'Nepal', suffixes: ['.np', '.com.np'] },
  nl: { name: 'Netherlands', suffixes: ['.nl'] },
  nz: { name: 'New Zealand', suffixes: ['.nz', '.co.nz'] },
  ni: { name: 'Nicaragua', suffixes: ['.ni'] },
  ne: { name: 'Niger', suffixes: ['.ne'] },
  ng: { name: 'Nigeria', suffixes: ['.ng', '.com.ng'] },
  mk: { name: 'North Macedonia', suffixes: ['.mk'] },
  no: { name: 'Norway', suffixes: ['.no'] },
  om: { name: 'Oman', suffixes: ['.om'] },
  pk: { name: 'Pakistan', suffixes: ['.pk', '.com.pk'] },
  pw: { name: 'Palau', suffixes: ['.pw'] },
  pa: { name: 'Panama', suffixes: ['.pa'] },
  pg: { name: 'Papua New Guinea', suffixes: ['.pg'] },
  py: { name: 'Paraguay', suffixes: ['.py'] },
  pe: { name: 'Peru', suffixes: ['.pe', '.com.pe'] },
  ph: { name: 'Philippines', suffixes: ['.ph', '.com.ph'] },
  pl: { name: 'Poland', suffixes: ['.pl'] },
  pt: { name: 'Portugal', suffixes: ['.pt'] },
  qa: { name: 'Qatar', suffixes: ['.qa'] },
  ro: { name: 'Romania', suffixes: ['.ro'] },
  ru: { name: 'Russia', suffixes: ['.ru'] },
  rw: { name: 'Rwanda', suffixes: ['.rw'] },
  kn: { name: 'Saint Kitts and Nevis', suffixes: ['.kn'] },
  lc: { name: 'Saint Lucia', suffixes: ['.lc'] },
  vc: { name: 'Saint Vincent and the Grenadines', suffixes: ['.vc'] },
  ws: { name: 'Samoa', suffixes: ['.ws'] },
  sm: { name: 'San Marino', suffixes: ['.sm'] },
  st: { name: 'Sao Tome and Principe', suffixes: ['.st'] },
  sa: { name: 'Saudi Arabia', suffixes: ['.sa', '.com.sa'] },
  sn: { name: 'Senegal', suffixes: ['.sn'] },
  rs: { name: 'Serbia', suffixes: ['.rs'] },
  sc: { name: 'Seychelles', suffixes: ['.sc'] },
  sl: { name: 'Sierra Leone', suffixes: ['.sl'] },
  sg: { name: 'Singapore', suffixes: ['.sg', '.com.sg'] },
  sk: { name: 'Slovakia', suffixes: ['.sk'] },
  si: { name: 'Slovenia', suffixes: ['.si'] },
  sb: { name: 'Solomon Islands', suffixes: ['.sb'] },
  so: { name: 'Somalia', suffixes: ['.so'] },
  za: { name: 'South Africa', suffixes: ['.za', '.co.za'] },
  ss: { name: 'South Sudan', suffixes: ['.ss'] },
  es: { name: 'Spain', suffixes: ['.es'] },
  lk: { name: 'Sri Lanka', suffixes: ['.lk'] },
  sd: { name: 'Sudan', suffixes: ['.sd'] },
  sr: { name: 'Suriname', suffixes: ['.sr'] },
  se: { name: 'Sweden', suffixes: ['.se'] },
  ch: { name: 'Switzerland', suffixes: ['.ch'] },
  sy: { name: 'Syria', suffixes: ['.sy'] },
  tj: { name: 'Tajikistan', suffixes: ['.tj'] },
  tz: { name: 'Tanzania', suffixes: ['.tz', '.co.tz'] },
  th: { name: 'Thailand', suffixes: ['.th', '.co.th'] },
  tl: { name: 'Timor-Leste', suffixes: ['.tl'] },
  tg: { name: 'Togo', suffixes: ['.tg'] },
  to: { name: 'Tonga', suffixes: ['.to'] },
  tt: { name: 'Trinidad and Tobago', suffixes: ['.tt'] },
  tn: { name: 'Tunisia', suffixes: ['.tn'] },
  tr: { name: 'Turkey', suffixes: ['.tr', '.com.tr'] },
  tm: { name: 'Turkmenistan', suffixes: ['.tm'] },
  tv: { name: 'Tuvalu', suffixes: ['.tv'] },
  ug: { name: 'Uganda', suffixes: ['.ug', '.co.ug'] },
  ua: { name: 'Ukraine', suffixes: ['.ua', '.com.ua'] },
  ae: { name: 'United Arab Emirates', suffixes: ['.ae'] },
  gb: { name: 'United Kingdom', suffixes: ['.uk', '.co.uk'] },
  uk: { name: 'United Kingdom', suffixes: ['.uk', '.co.uk'] },
  us: { name: 'United States', suffixes: ['.us'] },
  uy: { name: 'Uruguay', suffixes: ['.uy', '.com.uy'] },
  uz: { name: 'Uzbekistan', suffixes: ['.uz'] },
  vu: { name: 'Vanuatu', suffixes: ['.vu'] },
  va: { name: 'Vatican City', suffixes: ['.va'] },
  ve: { name: 'Venezuela', suffixes: ['.ve', '.com.ve'] },
  vn: { name: 'Vietnam', suffixes: ['.vn', '.com.vn'] },
  ye: { name: 'Yemen', suffixes: ['.ye'] },
  zm: { name: 'Zambia', suffixes: ['.zm'] },
  zw: { name: 'Zimbabwe', suffixes: ['.zw', '.co.zw'] }
};

export const getCountryName = (code) => {
  if (!code) return '';
  return countries[code.toLowerCase()]?.name || '';
};

export const getCountryDomainSuffixes = (code) => {
  if (!code) return [];
  return countries[code.toLowerCase()]?.suffixes || [];
};

// Get all countries as array for frontend dropdown
export const getAllCountries = () => {
  return Object.entries(countries).map(([code, data]) => ({
    code,
    name: data.name,
    suffixes: data.suffixes
  })).sort((a, b) => a.name.localeCompare(b.name));
};
